/* ============================================
   NewLook - Tailwind Configuration
   Include via <script src="js/tailwind.config.js"></script>
   AFTER loading Tailwind CDN
   ============================================ */

tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "primary":                   "#000000",
                "on-primary":                "#ffffff",
                "primary-container":         "#1c1b1b",
                "on-primary-container":      "#858383",
                "primary-fixed":             "#e5e2e1",
                "primary-fixed-dim":         "#c8c6c5",
                "on-primary-fixed":          "#1c1b1b",
                "on-primary-fixed-variant":  "#474746",
                "secondary":                 "#5d5f5f",
                "on-secondary":              "#ffffff",
                "secondary-container":       "#dddddd",
                "on-secondary-container":    "#606161",
                "secondary-fixed":           "#e2e2e2",
                "secondary-fixed-dim":       "#c6c6c6",
                "on-secondary-fixed":        "#1a1c1c",
                "on-secondary-fixed-variant":"#454747",
                "tertiary":                  "#000000",
                "on-tertiary":               "#ffffff",
                "tertiary-container":        "#1a1c1c",
                "on-tertiary-container":     "#838484",
                "tertiary-fixed":            "#e2e2e2",
                "tertiary-fixed-dim":        "#c6c6c7",
                "on-tertiary-fixed":         "#1a1c1c",
                "on-tertiary-fixed-variant": "#454747",
                "error":                     "#ba1a1a",
                "on-error":                  "#ffffff",
                "error-container":           "#ffdad6",
                "on-error-container":        "#93000a",
                "surface":                   "#fbf9f9",
                "surface-dim":               "#dbdad9",
                "surface-bright":            "#fbf9f9",
                "surface-variant":           "#e3e2e2",
                "surface-container-lowest":  "#ffffff",
                "surface-container-low":     "#f5f3f3",
                "surface-container":         "#efeded",
                "surface-container-high":    "#e9e8e7",
                "surface-container-highest": "#e3e2e2",
                "surface-tint":              "#5f5e5e",
                "on-surface":                "#1b1c1c",
                "on-surface-variant":        "#444748",
                "outline":                   "#747878",
                "outline-variant":           "#c4c7c7",
                "inverse-surface":           "#303031",
                "inverse-on-surface":        "#f2f0f0",
                "inverse-primary":           "#c8c6c5",
                "background":                "#fbf9f9",
                "on-background":             "#1b1c1c",
            },
            borderRadius: {
                "DEFAULT": "0.125rem",
                "lg":      "0.25rem",
                "xl":      "0.5rem",
                "full":    "0.75rem",
            },
            spacing: {
                "gutter":              "24px",
                "container-max-width": "1440px",
                "unit":                "4px",
                "margin-mobile":       "16px",
                "margin-desktop":      "40px",
            },
            fontFamily: {
                "display-lg":         ["Montserrat"],
                "headline-xl":        ["Montserrat"],
                "headline-xl-mobile": ["Montserrat"],
                "headline-lg":        ["Montserrat"],
                "body-lg":            ["Inter"],
                "body-md":            ["Inter"],
                "body-sm":            ["Inter"],
                "label-md":           ["Inter"],
            },
            fontSize: {
                "display-lg":         ["48px", { lineHeight: "1.1",  letterSpacing: "-0.02em", fontWeight: "700" }],
                "headline-xl":        ["32px", { lineHeight: "1.2",  fontWeight: "600" }],
                "headline-xl-mobile": ["28px", { lineHeight: "1.2",  fontWeight: "600" }],
                "headline-lg":        ["24px", { lineHeight: "1.3",  fontWeight: "600" }],
                "body-lg":            ["18px", { lineHeight: "1.6",  fontWeight: "400" }],
                "body-md":            ["16px", { lineHeight: "1.5",  fontWeight: "400" }],
                "body-sm":            ["14px", { lineHeight: "1.4",  fontWeight: "400" }],
                "label-md":           ["12px", { lineHeight: "1",    letterSpacing: "0.05em", fontWeight: "600" }],
            },
        },
    },
};